### ISSUE TITLE
listsprites link is broken

### ISSUE THREAD

**Issue by VladimirAlexiev** [Crashedmind/PlantUMLHitchhikersGuide#40]
https://crashedmind.github.io/PlantUMLHitchhikersGuide/NetworkUsersMachines/NetworkUsersMachines.html#view-all-the-icons-with-listsprites
shows a link `listprites` to the plantuml site, which is unspecific/broken.

I've searched the site, and the only place where `listprites` appears is https://plantuml.com/archimate-diagram#9a3dbeaa372bf477. 
Please link to that, but also mention the documentation is obsolete and the scope of `listprites` is wider (not just archimate diagrams), as you explain and as reflected in this issue https://forum.plantuml.net/8084/listsprite-for-stdlib

**Comment by VladimirAlexiev** [comment]
I added two sections to http://alphadoc.plantuml.com/doc/markdown/en/sprite#hdvb3xdf1doekdtyqgs2 . I think Arnoud said he'll update the doc after the summer.

**Comment by Crashedmind** [comment]
thanks @VladimirAlexiev.
Yes "listsprites" is an undocumented feature - that Arnaud pointed me towards - based on some code examples where I was obviously not aware of it - and did it the long/wrong way originally. (there are several others e.g. different ways of passing sprites as parameters. In hindsight, maybe I should have highlighted these as undocumented)

I don't plan to update this guide very often - likely when there's a new Plantuml feature I want to explore or promote.
Given you've updated the wiki - I'll wait for the update to be apporved/published - then some time later link to that. (I don't want to link to the archimate reference directly.)

Let me know if that makes sense - your input is appreciated!
thanks,
Chris

**Comment by VladimirAlexiev** [comment]
Makes sense.

Note: plantuml has MANY undocumented features, documenting them I'd tge purpose of Alphadoc and a structured task list is on github

**Comment by Crashedmind** [comment]
yeah - I had the conversation with Arnaud.

Ultimately, where it makes sense, the documentation should be in the source code ala javadoc etc... such that it **lives** with the source and can then be rendered / merged to a wiki or whichever human friendly format. 

Keywords would be an example where this makes sense. E.g. somewhere in the code is the "listsprites" functionality - and it would be trivial to add some auto-extractable description to the source to describe it. So when the source changes in the future, the documentation stays in sync.

**Comment by VladimirAlexiev** [comment]
Updated section http://alphadoc.plantuml.com/doc/markdown/en/sprite#jq1w8ezst4vzkdtyqu8b
