### ISSUE TITLE
Some links seem to be broken

### ISSUE THREAD

**Issue by Fabian1535** [Crashedmind/PlantUMLHitchhikersGuide#44]
Especially diagrams that include:

!include <awslib/mobile/all.puml>

And I can't figure it out how to fix it. Thanks,

**Comment by Crashedmind** [comment]
thanks @Fabian1535 

'looks like the folders changed in the source icon library.

https://github.com/plantuml/plantuml-stdlib/tree/master/awslib

https://github.com/plantuml/plantuml-stdlib/tree/master/awslib14 is the latest awslib as of now
So you could do e.g.
!include <awslib14/FrontEndWebMobile/all.puml>

**Comment by Fabian1535** [comment]
Awesome thank you, that worked.

Is there an easy way to see the new diagrams/locations with where they are located in the new folder structure?

**Comment by Crashedmind** [comment]
See https://crashedmind.github.io/PlantUMLHitchhikersGuide/github/githubFileFinder.html to easily find diagrams by name
