### ISSUE TITLE
Draw Color does not work with self-defined colors

### ISSUE THREAD

**Issue by SieDa** [Crashedmind/PlantUMLHitchhikersGuide#46]
As outlined in chapter 5 Colors, if I 
`!define mycolorBlue 4A80B6`
and use your procedure to output 
`$DrawColor("mycolorBlue") `
the result is not a box with my color-name inside but a box named with `4A80B6`.

Just to provide a simple example for more complex color settings and their documentation, can you explain why it does not work and how to change it? 

How to fix the procedure to provide my color name "`mycolorBlue`" in the box?
How to povide a second color to the procedure for the color name to be coloured by mycolorLightBlue defined by F8F7FF? 

```
@startuml

!unquoted procedure $DrawColor($colour)

    skinparam rectangle {
            backgroundColor<<$colour>> $colour
            borderColor<<$colour>> $colour
            shadowing<<$colour>> true
            BorderThickness<<$colour>> 1
        }

    rectangle $colour <<$colour>> as "<color:$colour></color>"

!endprocedure

!define mycolorBlue 4A80B6
package mycolors {
$DrawColor("mycolorBlue")
}
@enduml

```
![grafik](https://github.com/user-attachments/assets/03c1f02b-f50e-40fc-890d-133813ef79ed)

**Comment by SieDa** [comment]
On top to that effect, it is not possible to define relations between such entities, defined by that procedure, like: 

mycolorBlue --> mycolorGreen

**Comment by Crashedmind** [comment]
@SieDa thanks for the feedback

It would be best to ask these questions to the plantuml stdlib maintainers https://github.com/plantuml-stdlib
